import random
import datetime
from budget_core import Transaction, DEFAULT_CATEGORIES


def generate_test_transactions(num_days: int = 30, categories=None, base_seed: int = 42):
    if categories is None:
        categories = DEFAULT_CATEGORIES
    random.seed(base_seed)
    today = datetime.date.today()
    transactions = []
    for i in range(num_days):
        day = today - datetime.timedelta(days=i)
        num_per_day = random.choice([0, 1, 2, 3])
        for j in range(num_per_day):
            amount = round(random.uniform(0, 120), 2)
            if random.random() < 0.05:
                amount = 0.0
            if random.random() < 0.08:
                category = "Pets"
            else:
                category = random.choice(categories)
            description = f"Test expense {i}-{j}"
            notes = "" if random.random() > 0.5 else "autogenerated"
            transactions.append(Transaction(date=day, amount=amount, category=category, description=description, notes=notes))

    # edge cases: category not in list and zero spending
    transactions.append(Transaction(date=today, amount=10.0, category="UnknownCategory", description="Edge uncategorized", notes=""))
    transactions.append(Transaction(date=today - datetime.timedelta(days=1), amount=0.0, category=categories[0], description="Zero amount", notes="Edge case"))
    return transactions


def save_to_csv(transactions, filepath):
    from data_loader import save_transactions
    save_transactions(transactions, filepath)


if __name__ == '__main__':
    data = generate_test_transactions(30)
    save_to_csv(data, 'data/transactions.csv')
    print(f"Generated {len(data)} transactions in data/transactions.csv")
